In [2]:
import numpy as np

In [3]:
arr = np.array([1, 3, 4])

In [4]:
arr

array([1, 3, 4])

In [5]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
np.full((4, 6), 8)

array([[8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8]])

In [9]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
np.arange(1, 100, 9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [14]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [18]:
myarr = np.array([[2, 3, 4], [5, 6, 7], [8, 9, 0]])

In [19]:
myarr

array([[2, 3, 4],
       [5, 6, 7],
       [8, 9, 0]])

In [20]:
myarr.shape

(3, 3)

In [21]:
myarr.size

9

In [22]:
myarr.ndim

2

In [23]:
myarr.dtype

dtype('int64')

In [25]:
myarr = np.array([[2, 3, 4], [5, 6, 7], [8, 9, 0]], dtype='float32')

In [26]:
myarr

array([[2., 3., 4.],
       [5., 6., 7.],
       [8., 9., 0.]], dtype=float32)

In [27]:
myarr.astype('int32')

array([[2, 3, 4],
       [5, 6, 7],
       [8, 9, 0]], dtype=int32)

In [28]:
myarr = np.array([[2, 3, 4], [5, 6, 7], [8, 9, 0], [1, 1, 1]])

In [29]:
reshape = myarr.reshape((3, 4))

In [30]:
reshape

array([[2, 3, 4, 5],
       [6, 7, 8, 9],
       [0, 1, 1, 1]])

In [32]:
myarr.flatten()

array([2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 1, 1])