In [1]:
import numpy as np

In [3]:
arr = np.array([[2, 3, 4], [5, 6, 7], [8, 9, 0], [1, 1, 1]])

In [4]:
arr

array([[2, 3, 4],
       [5, 6, 7],
       [8, 9, 0],
       [1, 1, 1]])

In [5]:
flat = arr.flatten()

In [6]:
flat[0]

np.int64(2)

In [7]:
flat[3:6]

array([5, 6, 7])

In [8]:
flat[:5]

array([2, 3, 4, 5, 6])

In [9]:
flat[6:]

array([8, 9, 0, 1, 1, 1])

In [10]:
flat[::3]

array([2, 5, 8, 1])

In [11]:
flat

array([2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 1, 1])

In [12]:
b = flat[3:6]

In [13]:
b

array([5, 6, 7])

In [14]:
b[0] = 3444

In [15]:
flat

array([   2,    3,    4, 3444,    6,    7,    8,    9,    0,    1,    1,
          1])

In [16]:
b = flat[3:6].copy

In [18]:
flat[[1, 4, 6]]

array([3, 6, 8])

In [19]:
flat[flat>40]

array([3444])