In [1]:
import numpy as np

In [4]:
arr = np.array([i for i in range(1, 10)])

In [5]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr2 = arr.reshape(3, 3)

In [9]:
np.sum(arr2, axis=0)

array([12, 15, 18])

In [10]:
np.sum(arr2, axis=1)

array([ 6, 15, 24])

In [14]:
arr2[0:2, 1:3]

array([[2, 3],
       [5, 6]])

In [15]:
arr = np.array([i for i in range(1, 13)])

In [17]:
arr3D = arr.reshape(2, 2, 3)

In [18]:
arr3D

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [19]:
print(arr3D[:, 0, :])

[[1 2 3]
 [7 8 9]]
