In [2]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3, 4, 5])

In [4]:
arr ** 2

array([ 1,  4,  9, 16, 25])

In [6]:
arr + 10

array([11, 12, 13, 14, 15])

In [7]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])

In [8]:
arr2 = ([1, 2, 3])

In [9]:
result = arr1 + arr2

In [10]:
result

array([[2, 4, 6],
       [5, 7, 9]])