In [2]:
import numpy as np

In [4]:
arr = np.array([1.1, 2.2, 3.3])

In [7]:
arr2 = arr.astype('int32')

In [8]:
arr2

array([1, 2, 3], dtype=int32)

In [12]:
arr = np.array([i for i in range(1, 20)])

In [17]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [19]:
arr[arr%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [20]:
arr = np.array([i for i in range(1, 10)])

In [21]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
arr.reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])